---
- name: Read RedFish Power State using script module 
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Call GetSetPowerState python command
      script:
        #GetSetPowerStateREDFISH.py -ip 10.0.0.89 -u root -p r0gerwilc0 --set On
      args:
        executable: python3
      register: power_state

    - name: Print the  data received
      debug:
        var: power_state
